[project]
name = "sudoku"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "notebook>=7.5.6",
    "pymoo[full]>=0.6.1.6",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]

[build-system]
requires = ["uv_build>=0.11.12,<0.12"]
build-backend = "uv_build"
